services:
  - type: web
    name: bbpwdo-system
    env: php
    buildCommand: ""
    startCommand: ""
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: "postgresql://postgres:34060dbb-a862-4344-902a-c788ec856b78@db.bxkpgwugiwkhcnnjqosi.supabase.co:5432/postgres?sslmode=require"