services:
  - type: web
    name: bbpwdo-system
    env: docker
    buildCommand: docker build -t bbpwdo-system .
    startCommand: ""
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: "mysql://root:pzdNeueBLTcXStUoORVFzhwxtAgJUDtO@monorail.proxy.rlwy.net:22047/railway"