services:
  - type: web
    name: bbpwdo-system
    env: node
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: "mysql://root:tjpgTAzMdXsuvcdnHnxvgclTRTYiVEtv@mysql.railway.internal:3306/railway"